package:
  name: yank-dev
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0
  skip: True # [py2k]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pandas
    - numpy >=1.14
    - scipy
    - openmm >=7.3
    - mdtraj >=1.7.2
    - openmmtools >=0.17.0
    - pymbar
    - ambermini >=16.16.0
    - docopt
    - openmoltools >=0.7.5
    - mpiplus
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - cerberus ==1.1 # yank uses buggy cerberus 1.1 behavior as a feature ¯\_(ツ)_/¯
    - matplotlib
    - jupyter
    - pdbfixer

about:
  home: https://github.com/choderalab/yank
  license: MIT
  license_file: LICENSE
